#!/bin/bash

set -e

echo $"START: $(date)"

#cp ./scripts/github-pipeline/github-ormconfig.json ./ormconfig.json
#echo 'ormconfig.json: ';
#cat ormconfig.json

echo $'\n######################################################################';
echo 'Reinstalling npm modules...';
echo "$(date)"
echo $'######################################################################\n';

#rm -rf ./node_modules;
#npm i;

#echo $'\n######################################################################';
#echo 'Compiling typescript and preparing aws credentials';
#echo "$(date)"
#echo $'######################################################################\n';
#echo 'Typescript version:';
#tsc -v
#echo 'Typescript compilation...';
#tsc --outDir out
#echo 'Typescript compiled!';
#rm -rf ./out;



echo $'\n######################################################################';
echo 'Running DB migration on test database...';
echo "$(date)"
echo $'######################################################################\n';
echo $MYSQL_ROOT_PASSWORD
echo $MYSQL_PASSWORD
sudo systemctl start mysql
mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "CREATE SCHEMA \`vave-test\` DEFAULT CHARACTER SET utf8;"
mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "CREATE SCHEMA \`vave-test-logs\` DEFAULT CHARACTER SET utf8;"
mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "CREATE USER 'sys_dbdeploy'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD' REQUIRE SSL; GRANT CREATE, ALTER, DROP, REFERENCES, INDEX, SELECT, UPDATE, INSERT, DELETE ON *.* TO 'sys_dbdeploy'@'localhost'; FLUSH PRIVILEGES;"
mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "CREATE USER 'developer'@'localhost' IDENTIFIED BY 'developer' REQUIRE SSL; GRANT ALL PRIVILEGES ON *.* TO 'developer'@'localhost'; FLUSH PRIVILEGES;"
#mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "SELECT User, Host FROM user;"
#echo "MySQL database users"
echo "$(mysql -uroot -proot -e "SELECT User FROM mysql.user;")"
echo "selecting database"
echo "$(mysql -uroot -proot -e "show databases; use vave-test-logs; show tables;")"
#echo "migration queries"
mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "CREATE TABLE \`vave-test-logs\`.\`logs\` (
                          \`id\` BIGINT NOT NULL AUTO_INCREMENT,
                          \`createdAt\` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
                          \`level\` VARCHAR(12) NOT NULL,
                          \`message\` TEXT NULL,
                          \`obj\` TEXT NULL,
                          \`userId\` VARCHAR(36) NULL,
                          \`requestParams\` JSON NULL,
                          \`function\` VARCHAR(255) NULL,
                          \`source\` VARCHAR(255) NULL,
                          \`sourceIp\` varchar(255) NULL,
                          \`userAgent\` varchar(1024) NULL,
                          \`requestContext\` json NULL,
                          PRIMARY KEY (\`id\`),
                          UNIQUE INDEX \`UQ_id\` (\`id\` ASC),
                          INDEX \`IDX_createdAt\` (\`createdAt\` ASC, \`level\` ASC),
                          INDEX \`IDX_level\` (\`level\` ASC, \`createdAt\` ASC),
                          INDEX \`IDX_userId\` (\`userId\` ASC, \`createdAt\` ASC))
                        ENGINE = InnoDB
                        DEFAULT CHARACTER SET = utf8;"
echo 'DB created. User created.';



