name: ci-pipeline

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    env:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: sys_dbdeploy
        MYSQL_PASSWORD: P@sswd1
        MYSQL_DATABASE: vave-test
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{env.MYSQL_ROOT_PASSWORD}}
        ports:
        - 32574:3306
    steps:
    - uses: actions/checkout@v2
    - name: npm install, build, and test
      env:
          SUPER_SECRET: ${{ secrets.ACCESS_KEY }}
          MYSQL_ROOT_PASSWORD: ${{env.MYSQL_ROOT_PASSWORD}}
          MYSQL_USER: ${{env.MYSQL_USER}}
          MYSQL_PASSWORD: ${{env.MYSQL_PASSWORD}}
          MYSQL_DATABASE: ${{env.MYSQL_DATABASE}}
      run: |
        echo "$SUPER_SECRET"
        echo "checking pipeline file"
        echo "$MYSQL_PASSWORD"
        sh scripts/github-pipeline/github-pipeline

