name: ci-pipeline

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    env:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: sys_dbdeploy
        MYSQL_PASSWORD: P@sswd1
        MYSQL_DATABASE: vave-test
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{env.MYSQL_ROOT_PASSWORD}}
        ports:
        - 32574:3306
    steps:
    - uses: actions/checkout@v2
    - name: npm install, build, and test
      env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          MYSQL_ROOT_PASSWORD: ${{env.MYSQL_ROOT_PASSWORD}}
          MYSQL_USER: ${{env.MYSQL_USER}}
          MYSQL_PASSWORD: ${{env.MYSQL_PASSWORD}}
          MYSQL_DATABASE: ${{env.MYSQL_DATABASE}}
      run: |
        #curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        #unzip awscliv2.zip
        #sudo ./aws/install
        aws --version
        aws configure set aws_access_key_id "$ACCESS_KEY" --profile default
        aws configure set aws_secret_access_key "$SECRET_KEY" --profile default
        cat ~/.aws/credentials
        cat ~/.aws/config
        echo "$SUPER_SECRET"
        echo "checking pipeline file"
        echo "$MYSQL_PASSWORD"
        #sh scripts/github-pipeline/github-pipeline

