name: ci-pipeline

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 32574:3306
    steps:
    - uses: actions/checkout@v2
    - name: npm install, build, and test
      run: |
        echo "checking pipeline file"
        cd ..
        ls
        pwd
        ls -la
        chmod a+x scripts/github-pipeline/github-pipeline
        sh scripts/github-pipeline/github-pipeline
      env:
          MYSQL_USER: sys_dbdeploy
          MYSQL_PASSWORD: P@sswd1
          MYSQL_DATABASE: vave-test