on:
  push:
    branches:
      - UAT
      - Preprod
      - Dev
      - Prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variables for each environment
        run: |
           if [[ "${{ github.ref }}" == "refs/heads/uat" ]]; then
            echo "Setting UAT environment variables"
            echo "AWS_REGION=us-west-2" >> $GITHUB_ENV
            echo "AMPLIFY_ENV_NAME=uattwo.$AWS_REGION" >> $GITHUB_ENV
            elif [ "${GITHUB_REF##*/}" == "Preprod" ]; then
            echo "Setting Preprod environment variables"
            echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
            echo "AMPLIFY_ENV_NAME=preprod" >> $GITHUB_ENV
            elif [ "${GITHUB_REF##*/}" == "Dev" ]; then
            echo "Setting Dev environment variables"
            echo "AWS_REGION=us-east-2" >> $GITHUB_ENV
            echo "AMPLIFY_ENV_NAME=dev" >> $GITHUB_ENV
            elif [ "${GITHUB_REF##*/}" == "Prod" ]; then
            echo "Setting Prod environment variables"
            echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
            echo "AMPLIFY_ENV_NAME=prod" >> $GITHUB_ENV
            fi

      - name: Deploy to AWS
        run: |
          echo "Deploying to region $AWS_REGION with environment $AMPLIFY_ENV_NAME"
          # Your deployment commands here
          echo "$AMPLIFY_ENV_NAME"
