
name: ci-pipeline

on:
  push:
    branches:
      - uat2
env:
  AMPLIFY_PROJECT_ID: d16by1w8r30urm
  CLOUDFRONT_DISTRIBUTION_ID: E2FC181H5B6AM1
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        node-version: [20.11.1]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
       
    - name: Set base environment variables
      run: |
          echo "node -v"
          node -v
          if [[ "${{ github.ref }}" == "refs/heads/uat2" ]]; then

          echo AWSCLOUDFORMATIONCONFIG="{\
          \"configLevel\":\"project\",\
          \"useProfile\":true,\
          \"profileName\":\"default\",\
          \"region\":\"us-west-2\"\
          }" >> $GITHUB_ENV

          echo AMPLIFY="{\
          \"appId\":\"$AMPLIFY_PROJECT_ID\",\
          \"envName\":\"uattwo\",\
          \"defaultEditor\":\"none\"\
          }" >> $GITHUB_ENV

          echo PROJECTCONFIG="{\
          \"SourceDir\":\"src\",\
          \"DistributionDir\":\"dist/vave-web\",\\"BuildCommand\":\"npm run-script build -- --env=$ENV\",\
          \"StartCommand\":\"ng serve\"\
          }" >> $GITHUB_ENV

          echo FRONTEND="{\
          \"frontend\":\"javascript\",\
          \"framework\":\"react\",\
          \"config\":$PROJECTCONFIG\
          }" >> $GITHUB_ENV

          echo PROVIDERS="{\
          \"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
          }" >> $GITHUB_ENV

          
          #echo "AWSCLOUDFORMATIONCONFIG"="{\"configLevel\":\"project\",\"useProfile\":true,\"profileName\":\"default\",\"region\":\"eu-central-1\"\}" >> $GITHUB_ENV
            #echo "AMPLIFY"="{\"appId\":\"$AMPLIFY_PROJECT_ID\",\"envName\":\"uat\",\"defaultEditor\":\"none\"\}" >> $GITHUB_ENV
            #echo "PROJECTCONFIG"="{\"SourceDir\":\"src\",\"DistributionDir\":\"build\",\"BuildCommand\":\"npm run-script build\",\"StartCommand\":\"npm run-script start\"\}" >> $GITHUB_ENV
          fi
    - name: Set dependent environment variables
      run: |
          #echo "FRONTEND"="{\"frontend\":\"javascript\",\"framework\":\"react\",\"config\":$PROJECTCONFIG\}" >> $GITHUB_ENV
          #echo "PROVIDERS"="{\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\}" >> $GITHUB_ENV
    
    - name: Deploy to AWS
      run: |
          echo "Deploying to region $AWS_REGION with environment $AMPLIFY_ENV_NAME"
          # Your deployment commands here
          echo "AWSCLOUDFORMATIONCONFIG Name: $AWSCLOUDFORMATIONCONFIG"
          echo "AMPLIFY value: $AMPLIFY"
          echo "PROJECTCONFIG value is : $PROJECTCONFIG"
          echo "FRONTEND value is : $FRONTEND"
          echo "PROVIDERS value is : $PROVIDERS"

          echo $'\nConfiguring aws profile...'

          aws --version
          aws configure set aws_access_key_id "$ACCESS_KEY" --profile default
          aws configure set aws_secret_access_key "$SECRET_KEY" --profile default
          aws configure set region eu-central-1 --profile default
          aws configure set output json --profile default

          echo $'\n######################################################################';
          echo 'Installing AWS Amplify...';
          echo $'######################################################################\n';
          
          npm install -g @aws-amplify/cli
          
          echo 'Configure Amplify...'
          echo $'\namplify pull...'
          amplify pull \
          --amplify $AMPLIFY \
          --frontend $FRONTEND \
          --providers $PROVIDERS \
          --yes
          echo $'\namplify publish...'
          export NODE_OPTIONS=--max_old_space_size=4000
          amplify publish -c --yes

