name: ci-pipeline

on:
  push:
    branches:
      - uat
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Set base environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/uat" ]]; then
            echo "AWS_CLOUDFORMATION_CONFIG="{\"configLevel\":\"project\",\"useProfile\":true,\"profileName\":\"default\",\"region\":\"us-west-2\"}"" >> $GITHUB_ENV
          fi
 
      - name: Set dependent environment variables
        run: |
          echo "AMPLIFY="{\"appId\":\"$AMPLIFY_PROJECT_ID\",\"envName\":\"dev\",\"defaultEditor\":\"none\"}"" >> $GITHUB_ENV
 
      - name: Deploy to AWS
        run: |
          echo "Deploying to region $AWS_REGION with environment $AMPLIFY_ENV_NAME"
          # Your deployment commands here
          echo "Environment Name: $AWS_CLOUDFORMATION_CONFIG"
          echo "Amplify value: $AMPLIFY"
