name: ci-pipeline

on:
  push:
    branches:
      - uat
env:
  AMPLIFY_PROJECT_ID: d16by1w8r30urm
  CLOUDFRONT_DISTRIBUTION_ID: E2FC181H5B6AM1
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set base environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/uat" ]]; then
            echo "AWSCLOUDFORMATIONCONFIG={\\"configLevel\":\"project\",\\"useProfile\":true,\\"profileName\":\"default\",\\"region\":\"eu-central-1\"\}" >> $GITHUB_ENV
            echo "AMPLIFY="{\\"appId\":\"$AMPLIFY_PROJECT_ID\",\\"envName\":\"uat\",\\"defaultEditor\":\"none\"\}" >> $GITHUB_ENV
            echo "PROJECTCONFIG={\\"SourceDir\":\"src\",\\"DistributionDir\":\"build\",\\"BuildCommand\":\"npm.cmd run-script build\",\\"StartCommand\":\"npm.cmd run-script start\"\}" >> $GITHUB_ENV
          fi
 
      - name: Set dependent environment variables
        run: |
          echo "FRONTEND="{\\"frontend\":\"javascript\",\\"framework\":\"react\",\\"config\":$PROJECTCONFIG\}" >> $GITHUB_ENV
          echo "PROVIDERS="{\\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\}" >> $GITHUB_ENV
          
 
      - name: Deploy to AWS
        run: |
          echo "Deploying to region $AWS_REGION with environment $AMPLIFY_ENV_NAME"
          # Your deployment commands here
          echo "Environment Name: $AWSCLOUDFORMATIONCONFIG"
          echo "Amplify value: $AMPLIFY"
          echo "PROJECTCONFIG value is : $PROJECTCONFIG"
          echo "FRONTEND value is : $FRONTEND"
          echo "PROVIDERS value is : $PROVIDERS"
