name: ci-pipeline

on:
  push:
    branches:
      - uat
env:
  AMPLIFY_PROJECT_ID: y2ive7qvralmt3
  CLOUDFRONT_DISTRIBUTION_ID: EJD675VH0ZPN82
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set base environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/uat" ]]; then
            echo "AWSCLOUDFORMATIONCONFIG={\\"configLevel\":\"project\",\\"useProfile\":true,\\"profileName\":\"default\",\\"region\":\"us-west-2\"\}" >> $GITHUB_ENV
            echo "AMPLIFY="{\\"appId\":\"$AMPLIFY_PROJECT_ID\",\\"envName\":\"uattwo\",\\"defaultEditor\":\"none\"\}" >> $GITHUB_ENV
            echo "PROJECTCONFIG={\\"SourceDir\":\"src\",\\"DistributionDir\":\"dist/vave-web\",\\"BuildCommand\":\"npm run-script build -- --env=$ENV\",\\"StartCommand\":\"ng serve\"\}" >> $GITHUB_ENV
          fi
 
      - name: Set dependent environment variables
        run: |
          echo "FRONTEND="{\\"frontend\":\"javascript\",\\"framework\":\"react\",\\"config\":$PROJECTCONFIG\}" >> $GITHUB_ENV
          echo "PROVIDERS="{\\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\}" >> $GITHUB_ENV
          
 
      - name: Deploy to AWS
        run: |
          echo "Deploying to region $AWS_REGION with environment $AMPLIFY_ENV_NAME"
          # Your deployment commands here
          echo "Environment Name: $AWSCLOUDFORMATIONCONFIG"
          echo "Amplify value: $AMPLIFY"
          echo "PROJECTCONFIG value is : $PROJECTCONFIG"
          echo "FRONTEND value is : $FRONTEND"
          echo "PROVIDERS value is : $PROVIDERS"
